apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  template:
    spec:
      containers:
        - name: hello-world-app
          image: suvorovbt/hello-world-app:stable
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"