on:
  push:
    branches-ignore:
      - main
      - staging

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: |
          IMAGE_TAG=dev-${{ github.ref_name }}-${{ github.sha }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t suvorovbt/hello-world-app:${IMAGE_TAG} .
          docker push suvorovbt/hello-world-app:${IMAGE_TAG}

      - name: Deploy to dev environment
        run: |
          ./scripts/deploy.sh dev "${IMAGE_TAG}" "${{ github.ref_name }}"