on:
  push:
    branches-ignore:
      - main
      - staging

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: echo "IMAGE_TAG=dev-${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_ENV

      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t suvorovbt/hello-world-app:${IMAGE_TAG} .
          docker push suvorovbt/hello-world-app:${IMAGE_TAG}

      - name: Deploy to dev environment
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.image_tag }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          ./scripts/deploy.sh dev "${IMAGE_TAG}" "${GITHUB_REF_NAME}"