on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag from staging (e.g., staging-abc123)'
        required: true

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://my-app.com
    steps:
      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Deploy to production
        env:
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          ./scripts/deploy.sh prod "${IMAGE_TAG}"