name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy (e.g., dev-feature-x-a1b2c3d)'
        required: true

jobs:
  staging-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy to staging
        run: ./scripts/deploy.sh staging "${{ github.event.inputs.image_tag }}"